export const L1_SUPER_CATEGORY_OPTIONS: string[] = [
  'Men Fashion',
  'Women Fashion',
  'Home & Living',
  'Kids & Toys',
  'Personal Care & Wellness',
  'Mobiles & Tablets',
  'Consumer Electronics',
  'Appliances',
  'Automotive',
  'Beauty & Personal Care',
  'Home Utility',
  'Kids',
  'Grocery',
  'Women',
  'Home & Kitchen',
  'Health & Wellness',
  'Beauty & Makeup',
  'Personal Care',
  "Men'S Grooming",
  'Craft & Office Supplies',
  'Sports & Fitness',
  'Automotive Accessories',
  'Pet Supplies',
  'Office Supplies & Stationery',
  'Industrial & Scientific Products',
  'Musical Instruments',
  'Books',
  'Eye Utility',
  'Bags, Luggage & Travel Accessories',
  'Mens Personal Care & Grooming',
];

export const COLOR_OPTIONS: string[] = [
  'Aqua Blue',
  'Assorted',
  'Beige',
  'Black',
  'Blue',
  'Bolt Blue Marl',
  'Brick Red',
  'Bright Yellow',
  'Brown',
  'Butter Yellow',
  'Caramel Brown',
  'Charcoal Marl',
  'Classic Black',
  'Clean Slate',
  'Coffee Brown',
  'Coral',
  'Cream',
  'Crepe Pink',
  'Deep Green',
  'Deep Sea Blue',
  'Forest Green',
  'Gold',
  'Green',
  'Grey',
  'Grey Melange',
  'Heather Grey',
  'Ice Grey',
  'Indigo Blue',
  'Khaki',
  'Lavendar',
  'Lemon Yellow',
  'Maroon',
  'Metallic',
  'Midnight Navy',
  'Mint Green',
  'Multicolor',
  'Mustard',
  'Mustard Yellow',
  'Navy Blue',
  'Neon Green',
  'Nude',
  'Olive',
  'Olive Green',
  'Orange',
  'Pastel Grey',
  'Peach',
  'Pine Green',
  'Pink',
  'Purple',
  'Red',
  'Rust',
  'Silver',
  'Sporty Maroon',
  'Teal',
  'White',
  'Yellow',
];

export const FABRIC_OPTIONS: string[] = [
  'Acrylic',
  'Art Silk',
  'Bamboo',
  'Chambray',
  'Chanderi Cotton',
  'Chanderi Silk',
  'Chiffon',
  'Cotton',
  'Cotton Blend',
  'Cotton Cambric',
  'Cotton Linen',
  'Cotton Silk',
  'Crepe',
  'Denim',
  'Dupion Silk',
  'Elastane',
  'Georgette',
  'Jacquard',
  'Jute Cotton',
  'Jute Silk',
  'Khadi Cotton',
  'Kora Muslin',
  'Lace',
  'Linen',
  'Lycra',
  'Microfibre',
  'Modal',
  'Mulmul',
  'Net',
  'Nylon',
  'Organza',
  'Paper Silk',
  'Pashmina',
  'Poly Blend',
  'Poly Chiffon',
  'Poly Crepe',
  'Poly Georgette',
  'Poly Silk',
  'Polycotton',
  'Polyester',
  'Polypropylene',
  'Popcorn',
  'Rayon',
  'Rayon Slub',
  'Satin',
  'Shantoon',
  'Silk',
  'Silk Blend',
  'Soft Silk',
  'Super Net',
  'Supima Cotton',
  'Synthetic',
  'Taffeta Silk',
  'Tissue',
  'Tussar Silk',
  'Velvet',
  'Vichitra Silk',
  'Viscose Rayon',
  'Voile',
  'Wool',
];

export const FIT_SHAPE_OPTIONS: string[] = [
  'Boxy',
  'Compression',
  'Loose',
  'Oversize',
  'Regular',
  'Relaxed',
  'Slim',
  'Tailored',
];

export const GENERIC_NAME_OPTIONS: string[] = [
  'Accessories',
  'Bottom Wear',
  'Garment',
  'Others',
  'Sportswear',
  'Topwear',
  'Tshirts',
  'Undergarment',
];

export const NET_QUANTITY_OPTIONS: string[] = [
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
];

export const NECK_OPTIONS: string[] = [
  'Contrast Collar',
  'Cowl',
  'Dual Collar',
  'Henley',
  'High Neck',
  'Hood',
  'Mandarin',
  'Polo',
  'Racerback',
  'Round',
  'Scoop',
  'Shawl',
  'Square',
  'V-neck',
];

export const OCCASION_OPTIONS: string[] = [
  'Beach',
  'Casual',
  'Festive',
  'Formal',
  'Party',
];

export const PATTERN_OPTIONS: string[] = [
  'Checked',
  'Colorblocked',
  'Dyed/Washed',
  'Embellished',
  'Embroidered',
  'Printed',
  'Self-Design',
  'Solid',
  'Striped',
  'Woven Design',
  'Zari Woven',
];

export const PRINT_PATTERN_TYPE_OPTIONS: string[] = [
  '3D Print',
  'Abstract',
  'Animal',
  'Aztec',
  'Back Print',
  'Birthday Print',
  'Bohemian',
  'Botanical',
  'Brother Sister',
  'Buffalo Checks',
  'Camouflage',
  'Cartoons',
  'Checked',
  'Chevron',
  'Colorblocked',
  'Conversational',
  'Couple Print',
  'Cricket',
  'Ditsy Print',
  'Emoji',
  'Engineered Stripes',
  'Ethnic Motif',
  'Faded',
  'Fitness',
  'Floral',
  'Foil Print',
  'Football',
  'Friends',
  'Funky Print',
  'Game',
  'Geometric',
  'Gingham Checks',
  'Graphic Print',
  'Grid Tattersail Checks',
  'Heathered',
  'Holi',
  'Horizontal Stripes',
  'Houndstooth',
  'Independence Day/Indian Flag',
  'Mahakal',
  'Marshmellow',
  'Micro Check',
  'Micro Print',
  'Movie/Celebrity',
  'Newspaper Print',
  'Ombre',
  'Other Sports',
  'Paisley',
  'Pinstripes',
  'Placement Print',
  'Political Print',
  'Polka Dots',
  'Quirky',
  'Rainbow',
  'Regional',
  'Religious Print',
  'Rider Print',
  'Solid',
  'Superheroes',
  'Tartan Checks',
  'Tik Tok',
  'Tribal',
  'Typography',
  'Vertical Stripes',
  'Windowpane Checks',
  'Woven Design',
];

export const SLEEVE_LENGTH_OPTIONS: string[] = [
  'Long Sleeves',
  'Short Sleeves',
  'Sleeveless',
  'Three-Quarter Sleeves',
];

export const COUNTRY_OF_ORIGIN_OPTIONS: string[] = [
  'India',
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia-Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Rep',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czechia',
  'DRC Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea Bissau',
  'Guyana',
  'Haiti',
  'Holy See',
  'Honduras',
  'Iceland',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Palau',
  'Palestine State',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts & Nevis',
  'Saint Lucia',
  'St Vincent',
  'Samoa',
  'San Marino',
  'Sao Tome',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'UAE',
  'United Kingdom',
  'USA',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
  'Not Available',
];

export const SOLE_MATERIAL_OPTIONS: string[] = [
  'Airmix',
  'EVA',
  'Leather',
  'Phylon',
  'PU (Polyurethane)',
  'PVC',
  'Rubber',
  'Sheet',
  'TPR (Thermoplastic Rubber)',
  'Tuning Sheet',
];

export const FASTENING_OPTIONS: string[] = [
  'Backstrap',
  'Buckle',
  'Lace-Ups',
  'Slip-On',
  'Velcro',
  'Zipper',
  'No Fastening',
];

export const TOE_TYPE_OPTIONS: string[] = [
  'Open Toe',
  'Pointed Toe',
  'Peep Toe',
  'Round Toe',
  'Square Toe',
];

export const UPPER_MATERIAL_OPTIONS: string[] = [
  'Canvas',
  'Genuine Leather',
  'Mesh & Breathable Fabric',
  'Microfiber',
  'PU / Synthetic Leather',
  'Suede',
  'Synthetic',
  'Textile',
  'Velvet',
];
